def Complementing_a_DNA_strand(dna_sequence: str):
    trans_table = str.maketrans("ACGT", "TGCA")
    
    complementary_sequence = dna_sequence.translate(trans_table)
    
    reverse_complement = complementary_sequence[::-1]
    print("--- Complementary DNA Sequence ---")
    print(reverse_complement)
    return reverse_complement

def count_dna_nucleotides(sequence: str):
    
    counts = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    
    for letter in sequence:
        if letter in counts:
            counts[letter] += 1
            
    result = f"{counts['A']} {counts['C']} {counts['G']} {counts['T']}"
    
    print(result)
    return result

x ="GTTGGATTGAGCGGCCGCACTAGGCGTCAGAACTGCAAAAACTACGGATAAAATACTCACACTTCGGTCCTGGGGTTATCCCATGCGTAACACTAGTACAAGTTTCCTTTGTTCCGCGACATGACTGTTGGCTGATAACCCCGCCAGGTAGTTCCTCACCGTGCGTTAAACTTTTGTCGCATCCGTCTGAGGGAATTCGGAGCACATCACCTTCACCATACTTCACTTGATGCTACGAAATAATGACCGTTAAAGAGTATGGGCCCTATGATGACAACAGGAAGGTCACACGTATAGCGAGTTAGTCACGCGATGCATACGCTCTGTTAAAGCCACTCCACAGTGACACAGTTTTGCAATAAATACACGGTGACCGCATTTGCATGGACTAGTATTAGGTTGTCGCGTCTGTGTTCTCCAAGAAGAGATCTCTCGGTTTCGCTAGTTGCGGGATCGGCCGGGGGGCTGTCCTGTTGTTTAAAGGAAAAGGTACCTAGAGTGAGCGGCACCGCTAGCCGCCGGGCGAGAGCATTCCGTCATGAAATATGTGAAAATGGATGCTTGTCAAGGTAAGGCCCCCTAATCCAGCCTACCAGACGGGAATGTGAGCGTCAGAATTTCCGCTTCCCCTGGCCACAGGGTCTGATGATTTATAAATTCGACCACGTGACAGTGGGAATATGTAATGACTTATTGTTCCAATAGGCTTTGTACTGAACTAGCACTGGGGAGCTTCATTCAAACCTCACACTGTTCTGTTCATCCGTCGCGAAAGCGTGACGACACCGATAACCGCCTGTGCGCATCTAGGGATTTTCCCTATTATGTGTGTA"
count_dna_nucleotides(x)

Complementing_a_DNA_strand(x)