def count_dna_nucleotides(sequence: str):
    
    counts = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    
    for letter in sequence:
        if letter in counts:
            counts[letter] += 1
            
    result = f"{counts['A']} {counts['C']} {counts['G']} {counts['T']}"
    
    print(result)
    return result



x = "ATCCGTTCTGCTACACTTGACACCAATGGTCTAAATCCGGTACCGGAGCCGCGCACGTACCGTCGTACAAGTAAAGGGACAATTGTGCTGATATAGATACTCTGACCCAAGCTATTGTATTCCAGGTATTCAAGGTACGAGTAAAATTGCGCCACTGGGCTCAACCTCGTACCTGCCAGACGCATTGGAACCCAGATCGCGGGAGGTATCCGGTATCGCGAGAGTTGCCACCCACCTGTATCGTGTGGCGTGGGAGGCACTATGCCCCGGGTGCACACATTAGGACATTAAAGTTCTTTGTCACCAAACTAGCCACGCAACGAGAACATTGCGCAGAGGCTTGGTATCTCACCAAACAATCCACGTCAACTCAAATGGAGCGAGCTGTGTCCCCACCACCTGTTGACGAACCCCGAACCCGGGGGCTGCTATTAGATCCGCTTCCGCATTGAGAGGGAACCTCATAATAAACGATTTGACGTAGTATCCACATTGCCAAAGCCTGACGTTTTGCTATCCTTTTGGGAGGGCAACCGCGTCGGATTTCGTCCACTTGATGCGCGTAAAAGCAGATGCATCGCTAACATGTGGGGGTACAGCTAGATGGGAGACTCCGCTGCACACTATTCCTTTCGTCCCCCTGAAATTCGTGATGGAATACCTTTTCAAGCCTTAGCCAAGGGATGCAAGGTCCAGTATGTAGGACTAGACCCTTGCCGGCACAAGGTCCTTGTTTGGTACCGGCGGATCTGCGGTCTCACGTTAAAGATGCCGAAGCTCGTCTTCACATTGTATTTTGGTTAATAACGCACGCTCCGGTATGGACCCTAAGGATGATAGAG"

count_dna_nucleotides(x)