def transcribe_dna_to_rna(dna_sequence: str):
    rna_sequence = dna_sequence.replace('T', 'U')
    
    print("--- Transcribed RNA Sequence ---")
    print(rna_sequence)
    return rna_sequence

def count_dna_nucleotides(sequence: str):
    
    counts = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    
    for letter in sequence:
        if letter in counts:
            counts[letter] += 1
            
    result = f"{counts['A']} {counts['C']} {counts['G']} {counts['T']}"
    
    print(result)
    return result

x = "TCAGCCTATATTTATTACTTCAGACATCAACAGCTTCGCGCCGGTATGGCGCCGCCAGGCAGAATTACCGTTGCGGGACATGCCCGCGCGAGGCGGCACGACGTCGTCCATAGAAACCTCGCGAGATGGACATCTGCAATTTAAAAAGAATTACTGACACTGGGGATCAAAAGAATGTTCGCTGCGGGTAGCGCCTGCGACGATAACAGCTTCTCAGCTTTGTGGCCCTGAATTTCTTACTCTGAATCTCGTATGGGTGTCGCTGATCATGCCAATCCGAAGAGCCTCAGACCCGCTGGATGTAAGCTTAACGATTCTATTTGATACGTAACATGTGTGACCCCAAACAGATAGATCCACCATGGGGGATGAGCGCGAGAAAGTGGTTTCCCCCCCTCAAGATTGGATTACGGATCCCAGTTCTCAACCCTGACATTCCCGGAATGTCCGGGACAGCTTAGAAGAGGTGACCTCTTGGGCGCGGTGACGCGATATCATACACTACTGCAATATCTAACATGTATCTACGAGATCATGGATTAGAAGTGTAGTAGACACCTTCATCCTCTTCAGGGGCAAAGTTTCCGCGCCTTCGGAATGCAGTGATGATTGCCAGCAATTGGTTAGCTAAATTTAAATCTGCCTATTAGGGTGACTATCTACTATAGCAAATCGTAAGTCCTAATCCATTATGTACTGTGCCGCCCAAGTTTGCGATTGAAGAATCCCACCCCTCTTCATGCCTCTTTGCGCCGGACGCCGCAGACGCCAGGGACAGTTAGACCAGAGATAAACATGATTGTTAGTGCAGGAGCGAGCTCGAGCATTCGCACTTTATCGGCTTTATAATTCAGCCCAGCAAACTGAACCGATCCTTACATCAGTATTGTTCCAATAGGCGCGCGACCTATCCCACTAGGTCAAAATAGTCACCGCCACTATGTTAGTCAATGTGTTGGGTATGTAAACGGACTA"
count_dna_nucleotides(x)

transcribe_dna_to_rna(x)